// <auto-generated />
using ArtistApp.Server.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtistApp.Server.Migrations
{
    [DbContext(typeof(ArtistDbContext))]
    partial class ArtistDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.28");

            modelBuilder.Entity("ArtistApp.Server.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasMaxLength(5)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            Description = "Gold Pharaoh (Original Mix) is a song by Proof Db, available on SoundCloud. It is also available on Amazon UK, where it appears on the album Gold Pharoah along with other songs by Proof Db and Zayn Malik",
                            ReleaseYear = 2020,
                            Title = "Gold Pharoah"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 2,
                            Description = "Anti is the eighth studio album by Barbadian singer Rihanna. It was released on 28 January 2016 by Roc Nation and Westbury Road",
                            ReleaseYear = 2016,
                            Title = "Anti"
                        });
                });

            modelBuilder.Entity("ArtistApp.Server.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Artists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Zain Javadd Malik (born 12 January 1993), known professionally as Zayn Malik or simply Zayn, is a British singer. Malik auditioned as a solo contestant for the British music competition television series The X Factor in 2010",
                            Name = "Zayn Malik"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Robyn Rihanna Fenty born February 20, 1988) is a Barbadian singer, businesswoman, and actress",
                            Name = "Robyn Rihana Fenty"
                        });
                });

            modelBuilder.Entity("ArtistApp.Server.Entities.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            Description = "Remember the time When you were here inside my dream I wish you'll be mine, You're understanding what I mean",
                            Title = "Deep Spirit"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 2,
                            Description = "Needed Me is a mellowish dubstep-flavored electro-R&B song with trippy, trappy production, and a length of three minutes and five seconds",
                            Title = "Needed Me"
                        });
                });

            modelBuilder.Entity("ArtistApp.Server.Entities.Album", b =>
                {
                    b.HasOne("ArtistApp.Server.Entities.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("ArtistApp.Server.Entities.Track", b =>
                {
                    b.HasOne("ArtistApp.Server.Entities.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("ArtistApp.Server.Entities.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("ArtistApp.Server.Entities.Artist", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
